
name: Demo-GitHub-Actions-WorkFlow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository 
      - uses: actions/checkout@v3

      # Github Tag 
      - name: Github Tag Bump
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true
          INITIAL_VERSION: 2.7.2
          DEFAULT_BUMP: major
          
          
      
